// The public keys the extension trusts for its self-update (docs/extension.md §21): the primary signs every release,
// the backup stays offline. Both are SPKI DER, base64. The matching private keys are NOT in the repository
// (~/.config/interp-app/update-signing-*.pem). Generated by scripts/make-update-keys.mjs.
export const UPDATE_PUBLIC_KEYS = Object.freeze([
  'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE67m5VzjnoektDFyJIOh8su8WRMXZfkdTiU2BTOeL1JCrW/ZRXOTWN9aQ5v2Wc+TVMBvwBP8rvOANXUy8vv0LWQ==',
  'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExzq9s+5yRx95o6Ie6QKJJqE+AB7WQRP5aExJXAc4j4QMJc4mDh8gYema6Hbr9ogOo6+1Z+bFvxa6Mnvfg0a5Kg==',
]);
