import test from 'node:test';
import assert from 'node:assert/strict';
import { createPublicKey, generateKeyPairSync, webcrypto } from 'node:crypto';
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  DEFAULT_UPDATE_BACKUP_KEY_FILE, DEFAULT_UPDATE_KEY_FILE, UPDATE_KEY_DIR,
  generateUpdateKeyPair, publicKeyOf, signUpdateManifest, verifyUpdateManifest,
} from '../scripts/update-signing.mjs';
import { UPDATE_KEYS_MODULE, makeUpdateKeys, updateKeysSource } from '../scripts/make-update-keys.mjs';
import { UPDATE_PUBLIC_KEYS } from '../extension/lib/update-keys.js';

// docs/extension.md §21: the signing side of the extension's self-update. Throw-away keys only: every key here is
// generated by the test, lives under os.tmpdir() and is deleted afterwards. The owner's real private keys
// (~/.config/interp-app/) are never read, and makeUpdateKeys is only ever called with temp paths.

const repoRoot = fileURLToPath(new URL('../', import.meta.url));
const MANIFEST = Buffer.from('{\n  "format": 1,\n  "version": "0.5.0"\n}\n');

async function tempDir(t, prefix = 'interp-updsign-') {
  const directory = await mkdtemp(join(tmpdir(), prefix));
  t.after(() => rm(directory, { recursive: true, force: true }));
  return directory;
}

// Assembled at runtime: the release scan treats a literal PEM header in a file as a leaked key.
const PEM_BEGIN = ['-----BEGIN', 'PRIVATE KEY-----'].join(' ');
const PEM_END = ['-----END', 'PRIVATE KEY-----'].join(' ');

/** The base64 body of a PEM: the part that must never show up anywhere it should not. */
const pemBody = (pem) => pem.replace(/-----[A-Z ]+-----/g, '').replace(/\s+/g, '');
const flip = (bytes, index) => { const copy = Buffer.from(bytes); copy[index] ^= 0x01; return copy; };

// --- key pairs --------------------------------------------------------------------------------------------------------

test('generateUpdateKeyPair: a PKCS8 PEM and the matching SPKI base64 of a P-256 key, different every time', () => {
  const first = generateUpdateKeyPair();
  const second = generateUpdateKeyPair();
  assert.ok(first.privatePem.startsWith(`${PEM_BEGIN}\n`) && first.privatePem.endsWith(`\n${PEM_END}\n`), 'PKCS8 PEM');
  assert.match(pemBody(first.privatePem), /^[A-Za-z0-9+/]+=*$/);
  const details = createPublicKey({ key: Buffer.from(first.publicB64, 'base64'), format: 'der', type: 'spki' });
  assert.equal(details.asymmetricKeyType, 'ec');
  assert.equal(details.asymmetricKeyDetails.namedCurve, 'prime256v1');
  assert.equal(Buffer.from(first.publicB64, 'base64').length, 91, 'SPKI DER of an uncompressed P-256 point');
  assert.notEqual(first.privatePem, second.privatePem);
  assert.notEqual(first.publicB64, second.publicB64);
  assert.equal(publicKeyOf(first.privatePem), first.publicB64, 'the public key belongs to the private one');
  assert.notEqual(publicKeyOf(second.privatePem), first.publicB64);
});

// --- sign / verify ----------------------------------------------------------------------------------------------------

test('sign and verify: a round trip, the signature is the raw 64-byte r||s that WebCrypto verifies', async () => {
  const { privatePem, publicB64 } = generateUpdateKeyPair();
  const signature = signUpdateManifest(MANIFEST, privatePem);
  assert.match(signature, /^[A-Za-z0-9+/]+={0,2}$/);
  assert.equal(Buffer.from(signature, 'base64').length, 64, 'IEEE P1363, not DER');
  assert.equal(verifyUpdateManifest(MANIFEST, signature, publicB64), true);
  // Independent of the Node-side verifier: the primitive Chrome 116 has (ECDSA P-256 / SHA-256, raw signature).
  const key = await webcrypto.subtle.importKey('spki', Buffer.from(publicB64, 'base64'), { name: 'ECDSA', namedCurve: 'P-256' }, false, ['verify']);
  const algorithm = { name: 'ECDSA', hash: 'SHA-256' };
  assert.equal(await webcrypto.subtle.verify(algorithm, key, Buffer.from(signature, 'base64'), MANIFEST), true);
  assert.equal(await webcrypto.subtle.verify(algorithm, key, Buffer.from(signature, 'base64'), flip(MANIFEST, 5)), false);
  // A Uint8Array signs like a Buffer; the signature is randomized, both verify.
  const again = signUpdateManifest(new Uint8Array(MANIFEST), privatePem);
  assert.notEqual(again, signature);
  assert.equal(verifyUpdateManifest(MANIFEST, again, publicB64), true);
});

test('verify: another key, a tampered byte anywhere, a tampered or cut signature and junk all fail without throwing', () => {
  const { privatePem, publicB64 } = generateUpdateKeyPair();
  const other = generateUpdateKeyPair();
  const signature = signUpdateManifest(MANIFEST, privatePem);
  assert.equal(verifyUpdateManifest(MANIFEST, signature, other.publicB64), false, 'wrong key');
  for (const index of [0, 1, Math.floor(MANIFEST.length / 2), MANIFEST.length - 2, MANIFEST.length - 1]) {
    assert.equal(verifyUpdateManifest(flip(MANIFEST, index), signature, publicB64), false, `byte ${index}`);
  }
  assert.equal(verifyUpdateManifest(Buffer.concat([MANIFEST, Buffer.from(' ')]), signature, publicB64), false, 'an appended byte');
  assert.equal(verifyUpdateManifest(MANIFEST.subarray(0, MANIFEST.length - 1), signature, publicB64), false, 'a missing byte');
  const raw = Buffer.from(signature, 'base64');
  for (const index of [0, 31, 32, 63]) assert.equal(verifyUpdateManifest(MANIFEST, flip(raw, index).toString('base64'), publicB64), false, `signature byte ${index}`);
  assert.equal(verifyUpdateManifest(MANIFEST, raw.subarray(0, 63).toString('base64'), publicB64), false, 'cut signature');
  assert.equal(verifyUpdateManifest(MANIFEST, Buffer.concat([raw, Buffer.from([0])]).toString('base64'), publicB64), false, 'long signature');
  assert.equal(verifyUpdateManifest(MANIFEST, '', publicB64), false);
  assert.equal(verifyUpdateManifest(MANIFEST, signature, ''), false);
  assert.equal(verifyUpdateManifest(MANIFEST, signature, 'not a key'), false);
  assert.equal(verifyUpdateManifest(MANIFEST, null, publicB64), false);
});

test('sign: an invalid PEM, a public key, an encrypted key and keys of another type or curve are refused with one code and no key text', () => {
  const good = generateUpdateKeyPair();
  const curve = (namedCurve) => generateKeyPairSync('ec', { namedCurve }).privateKey.export({ type: 'pkcs8', format: 'pem' });
  const encrypted = generateKeyPairSync('ec', { namedCurve: 'prime256v1' }).privateKey
    .export({ type: 'pkcs8', format: 'pem', cipher: 'aes-256-cbc', passphrase: 'throw-away' });
  const publicPem = createPublicKey({ key: Buffer.from(good.publicB64, 'base64'), format: 'der', type: 'spki' }).export({ type: 'spki', format: 'pem' });
  const bad = {
    empty: '',
    junk: 'not a pem',
    truncated: good.privatePem.slice(0, good.privatePem.length - 40),
    'public key as private': publicPem,
    encrypted,
    'P-384': curve('secp384r1'),
    secp256k1: curve('secp256k1'),
    RSA: generateKeyPairSync('rsa', { modulusLength: 2048 }).privateKey.export({ type: 'pkcs8', format: 'pem' }),
    Ed25519: generateKeyPairSync('ed25519').privateKey.export({ type: 'pkcs8', format: 'pem' }),
  };
  for (const [name, pem] of Object.entries(bad)) {
    for (const call of [() => signUpdateManifest(MANIFEST, pem), () => publicKeyOf(pem)]) {
      assert.throws(call, (error) => {
        assert.equal(error.code, 'UPDATE_SIGNING_KEY_INVALID', name);
        assert.equal(error.message, 'UPDATE_SIGNING_KEY_INVALID', name);
        assert.equal(error.cause, undefined, `${name}: no cause that could carry the key`);
        const body = pemBody(pem);
        if (body) assert.equal(`${error.stack}${JSON.stringify(error)}`.includes(body.slice(0, 40)), false, `${name}: error text carries key text`);
        return true;
      });
    }
  }
  assert.equal(signUpdateManifest(MANIFEST, good.privatePem).length > 0, true, 'the good key still signs');
});

test('the default key files sit outside the repository, in ~/.config/interp-app, as .pem files', () => {
  assert.match(UPDATE_KEY_DIR, /\.config[\\/]interp-app$/);
  assert.equal(DEFAULT_UPDATE_KEY_FILE, join(UPDATE_KEY_DIR, 'update-signing-primary.pem'));
  assert.equal(DEFAULT_UPDATE_BACKUP_KEY_FILE, join(UPDATE_KEY_DIR, 'update-signing-backup.pem'));
  for (const file of [DEFAULT_UPDATE_KEY_FILE, DEFAULT_UPDATE_BACKUP_KEY_FILE]) {
    assert.equal(file.startsWith(repoRoot.endsWith(sep) ? repoRoot : repoRoot + sep), false, `${file} must not be inside the repository`);
  }
});

// --- the committed public keys ---------------------------------------------------------------------------------------

test('extension/lib/update-keys.js: two distinct, frozen P-256 public keys in exactly the form make-update-keys writes', async () => {
  assert.equal(Object.isFrozen(UPDATE_PUBLIC_KEYS), true);
  assert.equal(UPDATE_PUBLIC_KEYS.length, 2, 'primary + offline backup');
  assert.equal(new Set(UPDATE_PUBLIC_KEYS).size, 2);
  for (const key of UPDATE_PUBLIC_KEYS) {
    const parsed = createPublicKey({ key: Buffer.from(key, 'base64'), format: 'der', type: 'spki' });
    assert.equal(parsed.asymmetricKeyDetails.namedCurve, 'prime256v1');
    assert.equal(Buffer.from(parsed.export({ type: 'spki', format: 'der' })).toString('base64'), key, 'canonical base64');
  }
  const text = await readFile(join(repoRoot, 'extension', 'lib', 'update-keys.js'), 'utf8');
  assert.equal(text, updateKeysSource(UPDATE_PUBLIC_KEYS), 'the committed file is what the generator writes');
  assert.equal(/PRIVATE|BEGIN /.test(text), false);
});

// --- make-update-keys --------------------------------------------------------------------------------------------------

async function keyPaths(t) {
  const dir = await tempDir(t, 'interp-mkkeys-');
  const keyDir = join(dir, 'keys');
  const moduleDir = join(dir, 'module');
  await mkdir(moduleDir, { recursive: true });
  // ESM like the real extension/lib: a package.json next to the temp module makes its .js an ES module.
  await writeFile(join(moduleDir, 'package.json'), '{"type":"module"}\n');
  return {
    dir, keyDir, moduleDir,
    primaryFile: join(keyDir, 'primary.pem'), backupFile: join(keyDir, 'backup.pem'), publicOut: join(moduleDir, 'update-keys.js'),
  };
}

const exists = async (path) => { try { await stat(path); return true; } catch { return false; } };

test('makeUpdateKeys: writes two 0600 PEM files into the key dir and an importable module with the two matching public keys', async (t) => {
  const paths = await keyPaths(t);
  const result = await makeUpdateKeys({ keyDir: paths.keyDir, primaryFile: paths.primaryFile, backupFile: paths.backupFile, publicOut: paths.publicOut });
  assert.deepEqual(result, { primaryFile: paths.primaryFile, backupFile: paths.backupFile, publicOut: paths.publicOut });
  if (process.platform !== 'win32') {
    for (const file of [paths.primaryFile, paths.backupFile]) assert.equal((await stat(file)).mode & 0o777, 0o600, `${file} is private to the owner`);
    assert.equal((await stat(paths.keyDir)).mode & 0o077, 0, 'the key directory is not group/world accessible');
  }
  const primaryPem = await readFile(paths.primaryFile, 'utf8');
  const backupPem = await readFile(paths.backupFile, 'utf8');
  assert.notEqual(primaryPem, backupPem);
  const module = await import(`${pathToFileURL(paths.publicOut).href}?run=${Date.now()}`);
  assert.equal(module.UPDATE_PUBLIC_KEYS.length, 2);
  assert.notEqual(module.UPDATE_PUBLIC_KEYS[0], module.UPDATE_PUBLIC_KEYS[1], 'two distinct keys');
  assert.equal(Object.isFrozen(module.UPDATE_PUBLIC_KEYS), true);
  assert.equal(module.UPDATE_PUBLIC_KEYS[0], publicKeyOf(primaryPem), 'slot 0 is the primary');
  assert.equal(module.UPDATE_PUBLIC_KEYS[1], publicKeyOf(backupPem), 'slot 1 is the backup');
  // Each private key signs something the module's matching public key verifies, and not the other one.
  for (const [index, pem] of [[0, primaryPem], [1, backupPem]]) {
    const signature = signUpdateManifest(MANIFEST, pem);
    assert.equal(verifyUpdateManifest(MANIFEST, signature, module.UPDATE_PUBLIC_KEYS[index]), true);
    assert.equal(verifyUpdateManifest(MANIFEST, signature, module.UPDATE_PUBLIC_KEYS[1 - index]), false);
  }
  // The committed module must be public only.
  const source = await readFile(paths.publicOut, 'utf8');
  assert.equal(source, updateKeysSource(module.UPDATE_PUBLIC_KEYS));
  for (const pem of [primaryPem, backupPem]) assert.equal(source.includes(pemBody(pem).slice(0, 40)), false, 'no private key text in the module');
});

test('makeUpdateKeys: refuses to overwrite any existing key file or module (UPDATE_KEYS_EXIST) and writes nothing else', async (t) => {
  for (const existing of ['primaryFile', 'backupFile', 'publicOut']) {
    const paths = await keyPaths(t);
    await mkdir(paths.keyDir, { recursive: true });
    await writeFile(paths[existing], 'precious original');
    let generated = 0;
    await assert.rejects(
      makeUpdateKeys({
        keyDir: paths.keyDir, primaryFile: paths.primaryFile, backupFile: paths.backupFile, publicOut: paths.publicOut,
        generate: () => { generated += 1; return generateUpdateKeyPair(); },
      }),
      (error) => { assert.equal(error.code, 'UPDATE_KEYS_EXIST', existing); assert.equal(error.message, 'UPDATE_KEYS_EXIST'); return true; },
    );
    assert.equal(generated, 0, `${existing}: no key is even generated`);
    assert.equal(await readFile(paths[existing], 'utf8'), 'precious original', `${existing} untouched`);
    for (const other of ['primaryFile', 'backupFile', 'publicOut'].filter((name) => name !== existing)) {
      assert.equal(await exists(paths[other]), false, `${existing} exists: ${other} must not be created`);
    }
  }
});

test('makeUpdateKeys: a second run over its own output is refused and changes no byte', async (t) => {
  const paths = await keyPaths(t);
  const args = { keyDir: paths.keyDir, primaryFile: paths.primaryFile, backupFile: paths.backupFile, publicOut: paths.publicOut };
  await makeUpdateKeys(args);
  const snapshot = async () => [await readFile(paths.primaryFile, 'utf8'), await readFile(paths.backupFile, 'utf8'), await readFile(paths.publicOut, 'utf8')];
  const before = await snapshot();
  await assert.rejects(makeUpdateKeys(args), { code: 'UPDATE_KEYS_EXIST' });
  assert.deepEqual(await snapshot(), before);
});

test('makeUpdateKeys: its defaults point at ~/.config/interp-app and extension/lib/update-keys.js (never called here)', () => {
  assert.equal(UPDATE_KEYS_MODULE, join(repoRoot, 'extension', 'lib', 'update-keys.js'));
});
