// P3-32: the administrator policy editor's core (design-p3 §1.7), with no DOM
// and no browser globals, so the rules can be tested directly.
//
// Two boundaries this file exists to hold:
//   - An imported JSON is checked by the SAME validator the app runs
//     (app/policy/schema.js). There is no second, looser admin parser.
//   - Editing here never becomes the running app's policy. This module returns
//     a draft and a diff; publishing is a person copying a file into the
//     repository (P3-33), which is why nothing here calls the network.
//
// It also holds no secret: a shared-event key is generated by P3-34 and never
// travels through the policy draft or its export.
import { POLICY_SCHEMA_VERSION, validatePolicy } from '../policy/schema.js';

const isObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
const clone = (value) => (value === undefined ? undefined : JSON.parse(JSON.stringify(value)));

/** Field paths a draft may set, in the screen order of §1.7. */
export const EDITOR_SECTIONS = Object.freeze(['deployed', 'emergency', 'settings', 'sharedEvents',
  'pricing', 'review', 'export', 'sharedPayload']);
/** Keys that must never appear in a policy draft, whatever was imported. */
export const FORBIDDEN_KEYS = Object.freeze(['key', 'apiKey', 'secret', 'token', 'credential', 'password']);

/** A minimal valid draft to start from when nothing has been loaded. */
export function emptyPolicy({ publishedAt = '2026-01-01T00:00:00Z', minAppVersion = '0.7.0' } = {}) {
  return {
    schemaVersion: POLICY_SCHEMA_VERSION, revision: 1, publishedAt, validUntil: null, minAppVersion,
    emergency: { stopped: false, reason: null },
    features: { sequential: true, simultaneousDirect: true, hubListen: true, diagnostics: true,
      sharedKeys: false, rememberPersonalKey: true },
    settings: {}, notices: [], sharedEvents: [], hubControl: null, pricing: null,
  };
}

/** Every path in `value` whose last segment looks like a credential. */
export function findForbidden(value, path = '', out = []) {
  if (Array.isArray(value)) {
    value.forEach((item, index) => findForbidden(item, `${path}/${index}`, out));
    return out;
  }
  if (!isObject(value)) return out;
  for (const [name, item] of Object.entries(value)) {
    const next = path ? `${path}/${name}` : name;
    if (FORBIDDEN_KEYS.includes(name)) out.push(next);
    findForbidden(item, next, out);
  }
  return out;
}

/** Differences between the deployed policy and a draft, as readable paths. */
export function diffPolicy(deployed, draft, path = '', out = []) {
  if (deployed === draft) return out;
  const both = isObject(deployed) && isObject(draft);
  if (!both) {
    if (JSON.stringify(deployed ?? null) !== JSON.stringify(draft ?? null)) {
      out.push({ path: path || '/', from: deployed ?? null, to: draft ?? null });
    }
    return out;
  }
  for (const name of new Set([...Object.keys(deployed), ...Object.keys(draft)])) {
    diffPolicy(deployed[name], draft[name], path ? `${path}/${name}` : name, out);
  }
  return out;
}

/** What the change would do to people using the app right now (§1.7 step 6). */
export function reviewChange(deployed, draft) {
  const before = deployed ?? {};
  const after = draft ?? {};
  const stopped = after.emergency?.stopped === true && before.emergency?.stopped !== true;
  const released = before.emergency?.stopped === true && after.emergency?.stopped !== true;
  const disabled = [], enabled = [], locked = [], unlocked = [];
  for (const name of new Set([...Object.keys(before.features ?? {}), ...Object.keys(after.features ?? {})])) {
    const was = before.features?.[name] !== false;
    const now = after.features?.[name] !== false;
    if (was && !now) disabled.push(name);
    if (!was && now) enabled.push(name);
  }
  for (const name of new Set([...Object.keys(before.settings ?? {}), ...Object.keys(after.settings ?? {})])) {
    const was = before.settings?.[name]?.locked === true;
    const now = after.settings?.[name]?.locked === true;
    if (!was && now) locked.push(name);
    if (was && !now) unlocked.push(name);
  }
  return Object.freeze({
    stopped, released,
    disabledFeatures: Object.freeze(disabled.sort()),
    enabledFeatures: Object.freeze(enabled.sort()),
    lockedSettings: Object.freeze(locked.sort()),
    unlockedSettings: Object.freeze(unlocked.sort()),
    revisionFrom: before.revision ?? null,
    revisionTo: after.revision ?? null,
    changes: Object.freeze(diffPolicy(before, after).map((entry) => Object.freeze(entry))),
  });
}

/**
 * createPolicyEditor({ deployed?, now? }) -> frozen editor.
 *
 *   load(json)     → import text or an object; validated by the app's validator.
 *   setField(path, value) / getDraft()
 *   validate()     → { ok, issues } from the same validator the app runs.
 *   review()       → reviewChange(deployed, draft)
 *   bumpRevision() → the draft's revision + 1 over the deployed one.
 *   snapshot()     → frozen { draft, deployed, valid, issues, review, dirty }
 */
export function createPolicyEditor({ deployed = null, now = Date.now } = {}) {
  let draftValue = clone(deployed) ?? emptyPolicy();
  let deployedValue = clone(deployed) ?? null;
  let issues = Object.freeze([]);
  let loadError = null;

  const validateNow = () => {
    const result = validatePolicy(clone(draftValue), { now });
    issues = result.ok ? Object.freeze([]) : result.issues;
    return result;
  };
  validateNow();

  const setPath = (target, path, value) => {
    const parts = String(path).split('/').filter(Boolean);
    if (!parts.length) return false;
    let node = target;
    for (const part of parts.slice(0, -1)) {
      if (!isObject(node[part]) && !Array.isArray(node[part])) node[part] = {};
      node = node[part];
    }
    node[parts.at(-1)] = clone(value);
    return true;
  };

  return Object.freeze({
    getDraft: () => clone(draftValue),
    getDeployed: () => clone(deployedValue),
    get loadError() { return loadError; },
    /** Replace the draft from JSON text or an object. Never applied to the app. */
    load(input) {
      loadError = null;
      let parsed = input;
      if (typeof input === 'string') {
        try { parsed = JSON.parse(input); } catch { loadError = 'POLICY_JSON'; return false; }
      }
      if (!isObject(parsed)) { loadError = 'POLICY_JSON'; return false; }
      // A credential in an imported file is refused outright: the policy is a
      // public document and must never carry one, whatever produced the file.
      const forbidden = findForbidden(parsed);
      if (forbidden.length) { loadError = 'POLICY_CREDENTIAL'; return false; }
      draftValue = clone(parsed);
      validateNow();
      return true;
    },
    setField(path, value) {
      if (!setPath(draftValue, path, value)) return false;
      validateNow();
      return true;
    },
    setDeployed(policy) {
      deployedValue = clone(policy) ?? null;
      return deployedValue;
    },
    validate() {
      const result = validateNow();
      return Object.freeze({ ok: result.ok === true, issues });
    },
    review() { return reviewChange(deployedValue, draftValue); },
    /** The next revision after the deployed one, so a changed file is a new one. */
    bumpRevision() {
      const base = Math.max(Number(deployedValue?.revision) || 0, Number(draftValue.revision) || 0);
      draftValue.revision = base + 1;
      validateNow();
      return draftValue.revision;
    },
    snapshot() {
      return Object.freeze({
        draft: Object.freeze(clone(draftValue)),
        deployed: deployedValue === null ? null : Object.freeze(clone(deployedValue)),
        valid: issues.length === 0,
        issues,
        loadError,
        review: reviewChange(deployedValue, draftValue),
        dirty: JSON.stringify(draftValue) !== JSON.stringify(deployedValue ?? emptyPolicy()),
      });
    },
  });
}
